{
   "groups": [
      {
         "name": "alloy_controller",
         "rules": [
            {
               "alert": "SlowComponentEvaluations",
               "annotations": {
                  "description": "Component evaluations are taking too long under job {{ $labels.job }}, component_path {{ $labels.component_path }}, component_id {{ $labels.component_id }}.",
                  "summary": "Component evaluations are taking too long."
               },
               "expr": "sum by (cluster, namespace, job, component_path, component_id) (rate(alloy_component_evaluation_slow_seconds[10m])) > 0",
               "for": "15m",
               "labels": {
                  "severity": "warning"
               }
            },
            {
               "alert": "UnhealthyComponents",
               "annotations": {
                  "description": "Unhealthy components detected under job {{ $labels.job }}",
                  "summary": "Unhealthy components detected."
               },
               "expr": "sum by (cluster, namespace, job) (alloy_component_controller_running_components{health_type!=\"healthy\"}) > 0",
               "for": "15m",
               "labels": {
                  "severity": "warning"
               }
            }
         ]
      },
      {
         "name": "alloy_otelcol",
         "rules": [
            {
               "alert": "OtelcolReceiverRefusedSpans",
               "annotations": {
                  "description": "The receiver could not push some spans to the pipeline under job {{ $labels.job }}. This could be due to reaching a limit such as the ones imposed by otelcol.processor.memory_limiter.",
                  "summary": "The receiver pushing spans to the pipeline success rate is below 95%."
               },
               "expr": "(1 - (\n        sum by (cluster, namespace, job) (rate(otelcol_receiver_refused_spans_total{}[1m]))\n        /\n        sum by (cluster, namespace, job) (rate(otelcol_receiver_refused_spans_total{}[1m]) + rate(otelcol_receiver_accepted_spans_total{}[1m]))\n     )\n) < 0.95\n",
               "for": "10m",
               "labels": {
                  "severity": "warning"
               }
            },
            {
               "alert": "OtelcolReceiverRefusedMetrics",
               "annotations": {
                  "description": "The receiver could not push some metric points to the pipeline under job {{ $labels.job }}. This could be due to reaching a limit such as the ones imposed by otelcol.processor.memory_limiter.",
                  "summary": "The receiver pushing metrics to the pipeline success rate is below 95%."
               },
               "expr": "(1 - (\n        sum by (cluster, namespace, job) (rate(otelcol_receiver_refused_metric_points_total{}[1m]))\n        /\n        sum by (cluster, namespace, job) (rate(otelcol_receiver_refused_metric_points_total{}[1m]) + rate(otelcol_receiver_accepted_metric_points_total{}[1m]))\n     )\n) < 0.95\n",
               "for": "10m",
               "labels": {
                  "severity": "warning"
               }
            },
            {
               "alert": "OtelcolReceiverRefusedLogs",
               "annotations": {
                  "description": "The receiver could not push some log records to the pipeline under job {{ $labels.job }}. This could be due to reaching a limit such as the ones imposed by otelcol.processor.memory_limiter.",
                  "summary": "The receiver pushing logs to the pipeline success rate is below 95%."
               },
               "expr": "(1 - (\n        sum by (cluster, namespace, job) (rate(otelcol_receiver_refused_log_records_total{}[1m]))\n        /\n        sum by (cluster, namespace, job) (rate(otelcol_receiver_refused_log_records_total{}[1m]) + rate(otelcol_receiver_accepted_log_records_total{}[1m]))\n     )\n) < 0.95\n",
               "for": "10m",
               "labels": {
                  "severity": "warning"
               }
            },
            {
               "alert": "OtelcolExporterFailedSpans",
               "annotations": {
                  "description": "The exporter failed to send spans to their destination under job {{ $labels.job }}. There could be an issue with the payload or with the destination endpoint.",
                  "summary": "The exporter sending spans success rate is below 95%."
               },
               "expr": "(1 - (\n        sum by (cluster, namespace, job) (rate(otelcol_exporter_send_failed_spans_total{}[1m]))\n        /\n        sum by (cluster, namespace, job) (rate(otelcol_exporter_send_failed_spans_total{}[1m]) + rate(otelcol_exporter_sent_spans_total{}[1m]))\n     )\n) < 0.95\n",
               "for": "10m",
               "labels": {
                  "severity": "warning"
               }
            },
            {
               "alert": "OtelcolExporterFailedMetrics",
               "annotations": {
                  "description": "The exporter failed to send metric points to their destination under job {{ $labels.job }}. There could be an issue with the payload or with the destination endpoint.",
                  "summary": "The exporter sending metrics success rate is below 95%."
               },
               "expr": "(1 - (\n        sum by (cluster, namespace, job) (rate(otelcol_exporter_send_failed_metric_points_total{}[1m]))\n        /\n        sum by (cluster, namespace, job) (rate(otelcol_exporter_send_failed_metric_points_total{}[1m]) + rate(otelcol_exporter_sent_metric_points_total{}[1m]))\n     )\n) < 0.95\n",
               "for": "10m",
               "labels": {
                  "severity": "warning"
               }
            },
            {
               "alert": "OtelcolExporterFailedLogs",
               "annotations": {
                  "description": "The exporter failed to send log records to their destination under job {{ $labels.job }}. There could be an issue with the payload or with the destination endpoint.",
                  "summary": "The exporter sending logs success rate is below 95%."
               },
               "expr": "(1 - (\n        sum by (cluster, namespace, job) (rate(otelcol_exporter_send_failed_log_records_total{}[1m]))\n        /\n        sum by (cluster, namespace, job) (rate(otelcol_exporter_send_failed_log_records_total{}[1m]) + rate(otelcol_exporter_sent_log_records_total{}[1m]))\n     )\n) < 0.95\n",
               "for": "10m",
               "labels": {
                  "severity": "warning"
               }
            }
         ]
      }
   ]
}
